# 02: numpy revision

In [1]:
import numpy as np

### **indexing & slicing**

In [4]:
# creatnig an array to work with
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
# slicing an 1d array
print(f"basic slicing >> arr[2:7] -> {arr[2:7]}")
print(f"with step >> arr[1:8:2] -> {arr[1:8:2]}")
print(f"negative indexing >> arr[-3] -> {arr[-3]}")

basic slicing >> arr[2:7] -> [3 4 5 6 7]
with step >> arr[1:8:2] -> [2 4 6 8]
negative indexing >> arr[-3] -> 8


In [10]:
# creating an 2d array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(f"2d array:\n{arr_2d}")

2d array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# slicing an 2d array
print(f"speicfic element >> arr_2d[1, 2] -> {arr_2d[1, 2]}")
# syntax: array_var_name[row, column]

speicfic element >> arr_2d[1, 2] -> 6


In [19]:
print(f"entire row arr_2d[1] -> {arr_2d[1]}") # syntax: array_var_name[row]
print(f"entire column arr_2d[:, 1] -> {arr_2d[:, 1]}") # syntax: array_var_name[:, column]

entire row arr_2d[1] -> [4 5 6]
entire column arr_2d[:, 1] -> [2 5 8]


### **sorting**

In [18]:
# basic sorting (1d array)
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print(f"unsorted array: {unsorted}")
print(f"sorted array: {np.sort(unsorted)}")

unsorted array: [3 1 4 1 5 9 2 6]
sorted array: [1 1 2 3 4 5 6 9]


In [26]:
# creating 2d array
arr_2d_unsorted = np.array([[3, 1],
                            [1, 2],
                            [2, 3]])
print(f"unsorted 2d array:\n{arr_2d_unsorted}\n{'-----'*7}")

# sorting 2d array: column
print(f"sorted 2d array by column:\n{np.sort(arr_2d_unsorted, axis=0)}")
# syntax: np.sort(arr_2d_unsorted, axis=0) >> axis=0=column

print(f"{'-----'*7}")

# sorting 2d array: row
print(f"sorted 2d array by row:\n{np.sort(arr_2d_unsorted, axis=1)}")
# syntax: np.sort(arr_2d_unsorted, axis=1) >> axis=1=row

unsorted 2d array:
[[3 1]
 [1 2]
 [2 3]]
-----------------------------------
sorted 2d array by column:
[[1 1]
 [2 2]
 [3 3]]
-----------------------------------
sorted 2d array by row:
[[1 3]
 [1 2]
 [2 3]]


### **filter**

In [28]:
numbers = np.arange(1, 11)
print(f"array (var_name: numbers) -> {numbers}")

array (var_name: numbers) -> [ 1  2  3  4  5  6  7  8  9 10]


In [31]:
# filtering even numbers
even_numbers = numbers[numbers % 2 == 0]
print(f"even numbers from numbers_array: {even_numbers}")

even numbers from numbers_array: [ 2  4  6  8 10]
