# Numpy
- numerical library used in Python - generally for data understanding
- developed in 2005 by Travis Oliphant
- before that there were special mathematical tools (similar to Tara, Linga)

In [6]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [ ]:
# Fundamental data structure in numpy is a numpy_array
lis = [1, 2, 3, "@jkmloom", 5+5j, True, 1.2]
type(lis)

list

In [5]:
# Numpy stored data in a numpy_array
# List stores heterogenous data, while numpy_array stores homogenous data

In [6]:
# Why numpy?
# fastest programming language as of now -> C an C++ is one of the fastest
# numpy is based on C>> computation is fast when done using numpy
# due to array >> homogenous data makes it even faster
# numpy_array >> continuous data allocation

In [8]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
print(arr, type(arr))
# 'nd' in ndarray stands for n dimantional array

[1 2 3 4 5] <class 'numpy.ndarray'>


In [11]:
l = [1, 2, 3, 4, 5, "jkmloom"]
# numpy.ndarray is homogenous >> all the elements will be converted to single/similar data type
arr = np.array(l)
print(arr, type(arr))
print(arr[2], type(arr[2]))

['1' '2' '3' '4' '5' 'jkmloom'] <class 'numpy.ndarray'>
3 <class 'numpy.str_'>


In [14]:
l = [1, 2, 3, 4, 5.5]
print(np.array(l), type(l[2]))

[1.  2.  3.  4.  5.5] <class 'int'>


In [17]:
print(arr)
print(type(arr))

['1' '2' '3' '4' '5' 'jkmloom']
<class 'numpy.ndarray'>


In [24]:
# arr is an 1-dimentional array (1d)
arr.ndim
# where, ndim = number of dimantions
# numpy.ndarray = n-dinemtional array

1

In [25]:
# arr1 is a 2-dimentional array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)
print(type(arr1))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [27]:
print(f"Array Dimention: {arr1.ndim}D")

Array Dimention: 2D


In [30]:
# matrix is a specialized array of 2 dimentions
mat = np.matrix([1, 2, 3, 4])
print(mat)
print(type(mat))
print(f"mat dimention: {mat.ndim}D")

[[1 2 3 4]]
<class 'numpy.matrix'>
mat dimention: 2D


In [35]:
# number of [] pair = number of dimentions for a numpy.ndarray
# example:
array_var = np.array([[[1, 2], [3, 4], [5, 6]], [[9, 8], [7, 6], [9, 9]]])
print(array_var)
print(f"Array_Var Dimentions: {array_var.ndim}D")

[[[1 2]
  [3 4]
  [5 6]]

 [[9 8]
  [7 6]
  [9 9]]]
Array_Var Dimentions: 3D


In [37]:
# more was to convert the array
l = [1, 2, 3]
np.asarray(l)
# initially numpy.asarray() was the main function used to convert list to array
# numpy.array() was introduced later on

array([1, 2, 3])

In [39]:
np.asanyarray([1, 2, 3])
# numpy.asanyarray() will convert the input to a ndarray
# but if the input is already an array or subclass of array it'll simply pass through it

array([1, 2, 3])

In [40]:
print(mat)
np.asanyarray(mat)

[[1 2 3 4]]


matrix([[1, 2, 3, 4]])

In [42]:
# convert tuple to an array
t = ([1, 2, 3], [4, 5, 6])
print(type(t))

<class 'tuple'>


In [46]:
tuple_to_array = np.array(t)
print(tuple_to_array)
print(f"{'---'*5}\ntuple_to_array:\n{'---'*5}\nType: {type(tuple_to_array)}\nArray Dimentions: {tuple_to_array.ndim}D")

[[1 2 3]
 [4 5 6]]
---------------
tuple_to_array:
---------------
Type: <class 'numpy.ndarray'>
Array Dimentions: 2D


In [50]:
# accessing elemets of an array
print(f"Array: {arr}")
print(f"0th element of array: {arr[0]}")

Array: ['1' '2' '3' '4' '5' 'jkmloom']
0th element of array: 1


In [52]:
# array is mutable
print(f"Array (before): {arr}")
arr[0] = 5
arr[-1] = "@jkmloom"
print(f"Array (after): {arr}")

Array (before): ['5' '2' '3' '4' '5' 'jkmloom']
Array (after): ['5' '2' '3' '4' '5' '@jkmloom']


In [ ]:
ar = [1, 2, 3, 4, 5]
a = ar # 'a' and 'ar' will point to same memeory location
# can on any will be reflecte on both
print(f"a: {a}")
print(f"ar: {ar}")

a: [1, 2, 3, 4, 5]
ar: [1, 2, 3, 4, 5]


In [58]:
# shallow copy >> chane in one array will leadto change in the other array
a[0] = 50
print(f"a (after): {a}")
print(f"ar (after): {ar}")

a (after): [50, 2, 3, 4, 5]
ar (after): [50, 2, 3, 4, 5]


In [62]:
# Deep Copy >> different memory location for similar data
b = a.copy()
print(f"Array a: {a}\nArray b: {b}")

Array a: [50, 2, 3, 4, 5]
Array b: [50, 2, 3, 4, 5]


In [63]:
b[0] = 55
print(f"Array a: {a}\nArray b: {b}")

Array a: [50, 2, 3, 4, 5]
Array b: [55, 2, 3, 4, 5]


In [66]:
# Multiple approches to generate array

# Construct an array be executing a function over each coordinate
arr1 = np.fromfunction(lambda i, j: i==j, (3, 3))
print(arr1)

[[ True False False]
 [False  True False]
 [False False  True]]


In [67]:
print(f"Array Dimention (arr1): {arr1.ndim}D")
print(f"Shape of Array (arr1): {arr1.shape}")

Array Dimention (arr1): 2D
Shape of Array (arr1): (3, 3)


In [68]:
arr1.size # returns number of elements in an array

9

In [69]:
np.fromfunction(lambda i, j: i*j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [1]:
# another way for creating array
for i in range(5):
    print(i, end=" ")

0 1 2 3 4 

In [2]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [3]:
variable_array = [i for i in range(5)]
print(f"Variable: {variable_array}\nVariable Type: {type(variable_array)}")

Variable: [0, 1, 2, 3, 4]
Variable Type: <class 'list'>


In [4]:
iterator = (i for i in range(5))
print(iterator)

<generator object <genexpr> at 0x000001DBEB046EC0>


In [7]:
np.fromiter(iterator, int)

array([0, 1, 2, 3, 4])

In [10]:
np.fromstring('22 23 24', sep=" ")

array([22., 23., 24.])

In [14]:
# dtype by default is float
np.fromstring('22 23 24', sep=" ", dtype=int)
# in this case >> values inside string s=hould be numerical

array([22, 23, 24])

In [17]:
# for using string character >> use split
string = "Jatin, Aman, Kaushik"
string.split(",")

['Jatin', ' Aman', ' Kaushik']

In [18]:
np.array(string.split(", "))

array(['Jatin', 'Aman', 'Kaushik'], dtype='<U7')

In [19]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
# another menthod in numpy for generating a sequence from the above cell
np.arange(1, 10)
# arange >> returns evenly spacified values withing a given interval
# by default >> step=1 [[ variable.arange(start, stop, step) ]]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1, 10, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [24]:
np.linspace(1, 5, 10) # returns 10 numbers in between 1-5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])