In [1]:
import numpy as np

In [9]:
# return an array of zeros for a given dimention and size
np.zeros(3)

array([0., 0., 0.])

In [10]:
# dtype is used to define the data type (default=float)
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
array_var = np.zeros((3, 4), dtype=int)
print(f"Array:\n{array_var}\nDimentions: {array_var.ndim}D")

Array:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Dimentions: 2D


In [14]:
# return an array filled with ones
np.ones((3, 4), dtype=int)
# default dtype=float

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [17]:
# creating an array of twos
array_var = np.ones((3, 3), dtype=int)*2
print(f"Array:\n{array_var}")

Array:
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [19]:
# another method
np.array([[2, 2 ,2], [2, 2, 2], [2, 2, 2]])

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [30]:
# creating an 3D array
print(f"1D Array: {np.zeros(2)}")
print(f"{'---'*12}\n2D Array:\n{np.zeros((2, 2))}")
print(f"{'---'*12}\n3D Array:\n{np.zeros((3, 2, 2))}") 

1D Array: [0. 0.]
------------------------------------
2D Array:
[[0. 0.]
 [0. 0.]]
------------------------------------
3D Array:
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [31]:
array_3d = np.zeros((3, 3, 4), dtype=int)
print(f"Array:\n{array_3d}")
print(f"Dimantions: {array_3d.ndim}D")

Array:
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
Dimantions: 3D


In [6]:
# creating 4D array
array_4d = np.ones((1, 1, 3, 4), dtype=int)
print(f"Array:\n{array_4d}")
print(f"Dimentions: {array_4d.ndim}D")

Array:
[[[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]]
Dimentions: 4D


In [10]:
# creating 5D array
array_5d = np.ones((1, 1, 1, 3, 4), dtype=int)*5
print(f"Array:\n{array_5d}")
print(f"Dimentions: {array_5d.ndim}D")

Array:
[[[[[5 5 5 5]
    [5 5 5 5]
    [5 5 5 5]]]]]
Dimentions: 5D


In [14]:
# arithmetic operations with ndarray
arr = np.zeros((3, 4), dtype=int)
print(arr + 5)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [13]:
a = arr + 5
a * 2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [15]:
print(f"Array:\n{a}")

Array:
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [17]:
a-1 # will reduce 1 from all the elements of the array 'a'

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [19]:
# create an identity matrix using numpy
np.eye(3)
# default dtype=float

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

> An identity matrix is always a square matrix.

In [27]:
np.empty((2, 2), dtype=int)
# entries of the array are gonna be anything at random

array([[93974237588365,              0],
       [93996476078992, 93996481326320]])

In [31]:
# random module
import random
random.choice((1, 2, 3, 4, 5))

5

In [32]:
random.choice("@jkmloom")

'l'

In [36]:
# random number using random.randrange(start, end)
random.randrange(1, 10)

3

In [38]:
# generate any random number between 0(included) - 1(excluded)
random.random()

0.30891541679901835

In [42]:

# shuffling values randomly
list_var = [1, 2, 3, 4, 5]
print(f"List: {list_var}")

random.shuffle(list_var)
print(f"Shuffled List: {list_var}")

List: [1, 2, 3, 4, 5]
Shuffled List: [4, 3, 1, 2, 5]


In [48]:
# random number from start_value to end_value with uniform distribution
random.uniform(7, 14)
# uniforom distribution >> probablity of getting thiis value is equal to the probablity of gettign any other value

7.617157353581605

In [49]:
# with time numpy included a random module inbuilt
# for most part it's calling the same random module we were dealing with in the previous cells

In [52]:
# random numbers related concepts in numpy
np.random.random_sample()

0.8922878538338376

In [54]:
# create an 1D array of random numbers using np.random.random_sample() 
np.random.random_sample((5))

array([0.07835994, 0.18205404, 0.99956093, 0.09469378, 0.88383809])

In [56]:
# create an 2D array of random numbers using np.random.random_sample()
np.random.random_sample((3, 3))

array([[0.89406683, 0.09499977, 0.38211382],
       [0.0203459 , 0.23641769, 0.55886927],
       [0.88956659, 0.46975594, 0.51438529]])

In [4]:
# another method
np.random.rand(4)

array([0.25581394, 0.44914849, 0.84269566, 0.33994511])

In [5]:
# create an 3D array of random numbers
np.random.rand(2, 3)

array([[0.46552814, 0.61654013, 0.50447343],
       [0.47890268, 0.55411171, 0.8872974 ]])

In [6]:
array_3d = np.random.rand(2, 3)
print(f"Array:\n{array_3d}\nDimentions: {array_3d.ndim}D")

Array:
[[0.41697281 0.64319772 0.76083741]
 [0.26922952 0.3085428  0.95384335]]
Dimentions: 2D


In [7]:
# syntax >> np.random.randn()
# returns sample from the standard normal distribution
np.random.randn(2, 3)

array([[-0.86348844,  2.06156286,  0.19723096],
       [-0.55614147, -0.69687528,  0.39086131]])

In [14]:
# array of random integers
np.random.randint(1, 5, size=(3, 4))
# np.random.randint(start, end, size=(rows, columns))

array([[2, 4, 3, 4],
       [2, 4, 1, 3],
       [4, 1, 3, 1]])

In [2]:
array_var = np.random.randint(1, 5, size=(3, 4))
print(f"Array:\n{array_var}\nDimentions: {array_var.ndim}D")

Array:
[[3 2 3 2]
 [2 1 4 2]
 [2 3 2 4]]
Dimentions: 2D


In [19]:
print("Array Shape:", array_var.shape)
print(f"Array Size: {array_var.size}")

Array Shape: (3, 4)
Array Size: 12


In [21]:
# reshaping an array
array_var.reshape(2, 6)
# returns an array containing the same data but with a new shape

array([[4, 4, 4, 2, 3, 2],
       [1, 1, 3, 3, 3, 3]])

In [27]:
array_var.reshape(2, 6)
# reshaping can only be done to a share that can contain all the elements from the original array

array([[4, 4, 4, 2, 3, 2],
       [1, 1, 3, 3, 3, 3]])

In [4]:
# case when the row or column is unknown while reshaping the array
# use any negative value for the unknown (row or column)
array_var.reshape(4, -1)

array([[3, 2, 3],
       [2, 2, 1],
       [4, 2, 2],
       [3, 2, 4]])

In [10]:
array_var.reshape(12, -1)

array([[3],
       [2],
       [3],
       [2],
       [2],
       [1],
       [4],
       [2],
       [2],
       [3],
       [2],
       [4]])

In [12]:
# returns original array
array_var.reshape(12,-1).base

array([[3, 2, 3, 2],
       [2, 1, 4, 2],
       [2, 3, 2, 4]])

In [ ]:
# reshaping array in different dimentions
print(f"Original Array:\n{array_var}\n\n{"***"*12}")
array_var.reshape(2, 2, 3)
# product of the value passed through .reshape() shouold be equal to original array size

Original Array:
[[3 2 3 2]
 [2 1 4 2]
 [2 3 2 4]]

************************************


array([[[3, 2, 3],
        [2, 2, 1]],

       [[4, 2, 2],
        [3, 2, 4]]])

In [18]:
print("New Array Shape: 4D\n", array_var.reshape(1, 2, 2, 3))

New Array Shape: 4D
 [[[[3 2 3]
   [2 2 1]]

  [[4 2 2]
   [3 2 4]]]]


In [19]:
array_var.reshape(4, 3, 1)

array([[[3],
        [2],
        [3]],

       [[2],
        [2],
        [1]],

       [[4],
        [2],
        [2]],

       [[3],
        [2],
        [4]]])

In [21]:
# conditions on array
array1 = np.random.randint(1, 10, (5, 6))
print(f"Array:\n{array1}")

Array:
[[1 8 5 6 7 7]
 [2 4 2 9 2 3]
 [1 1 3 7 7 4]
 [5 9 7 3 9 3]
 [2 1 8 5 9 7]]


In [24]:
print(f"Array shape: {array1.shape}")
print(f"Array size; {array1.size}")
print(f"Array dimention: {array1.ndim}D")

Array shape: (5, 6)
Array size; 30
Array dimention: 2D


In [26]:
# checl the positions where the value is true/false based on a defined value
array1 > 5

array([[False,  True, False,  True,  True,  True],
       [False, False, False,  True, False, False],
       [False, False, False,  True,  True, False],
       [False,  True,  True, False,  True, False],
       [False, False,  True, False,  True,  True]])

In [28]:
# following method will return the exact value at those positions
array1[array1 > 5]
# syntax >> array_name[condition]

array([8, 6, 7, 7, 9, 7, 7, 9, 7, 9, 8, 9, 7])

In [29]:
# another example
array1[array1 > 1]

array([8, 5, 6, 7, 7, 2, 4, 2, 9, 2, 3, 3, 7, 7, 4, 5, 9, 7, 3, 9, 3, 2,
       8, 5, 9, 7])

In [33]:
# to access elements in an array
print(array1[0])
print(array1[2])

[1 8 5 6 7 7]
[1 1 3 7 7 4]


In [34]:
# accessing a specific element
array1[1][2]

np.int64(2)

In [35]:
print(f"Array:\n{array1}")
# suppose we're accessing the element at (3, 1)
array1[3][1]

Array:
[[1 8 5 6 7 7]
 [2 4 2 9 2 3]
 [1 1 3 7 7 4]
 [5 9 7 3 9 3]
 [2 1 8 5 9 7]]


np.int64(9)

In [38]:
# returns a specific part of an array
array1[0:3]

array([[1, 8, 5, 6, 7, 7],
       [2, 4, 2, 9, 2, 3],
       [1, 1, 3, 7, 7, 4]])

In [39]:
# 0th to 2nd row and 0th to 3nd column
array1[0:3, [0,2]]

array([[1, 5],
       [2, 2],
       [1, 3]])

In [40]:
# slicing on both rows and columns together
print(f"Original Array:\n{array1}")

Original Array:
[[1 8 5 6 7 7]
 [2 4 2 9 2 3]
 [1 1 3 7 7 4]
 [5 9 7 3 9 3]
 [2 1 8 5 9 7]]


In [43]:
# slicing an array
array1[0:3, 1:4]

array([[8, 5, 6],
       [4, 2, 9],
       [1, 3, 7]])

In [44]:
array1[0:3, [0, 1]]

array([[1, 8],
       [2, 4],
       [1, 1]])

In [45]:
array1[0] # returns only one row

array([1, 8, 5, 6, 7, 7])

In [46]:
array1[0, [1, 3]]

array([8, 6])

In [48]:
array1[2:4, [0, 3]]

array([[1, 7],
       [5, 3]])

In [52]:
# mathematical operations on two arrays
array1 = np.random.randint(1, 3, (3, 3))
array2 = np.random.randint(1, 3, (3, 3))

print(f"Array 1:\n{array1}\n{"**"*12}\nArray 2:\n{array2}")

Array 1:
[[1 2 2]
 [2 2 2]
 [2 2 1]]
************************
Array 2:
[[2 1 2]
 [1 1 2]
 [1 2 2]]


In [54]:
# adding two arrays
array1 + array2

array([[3, 3, 4],
       [3, 3, 4],
       [3, 4, 3]])

In [55]:
# perform substraction on array
array1 - array2

array([[-1,  1,  0],
       [ 1,  1,  0],
       [ 1,  0, -1]])

In [57]:
# multiplication of two arrays
array1 * array2
# this multiplicaiton is done index wise (not actual matrix multiplication)

array([[2, 2, 4],
       [2, 2, 4],
       [2, 4, 2]])

In [59]:
# put both the arrays together on output screen (do nothing just print)
array1, array2

(array([[1, 2, 2],
        [2, 2, 2],
        [2, 2, 1]]),
 array([[2, 1, 2],
        [1, 1, 2],
        [1, 2, 2]]))

In [62]:
# dividing two arrays (index wise)
array1/array2

array([[0.5, 2. , 1. ],
       [2. , 2. , 1. ],
       [2. , 1. , 0.5]])

In [64]:
# in numpy a number divided by zero returns infinity
# x/0 = infinity

In [66]:
# matrix >> matrix is a special 2d array
# multiplication of a matrix is differnt from index wise multiplication of an 2D array
array1 @ array2

array([[ 6,  7, 10],
       [ 8,  8, 12],
       [ 7,  6, 10]])

In [67]:
# another method o fmatrix multiplication
np.dot(array1, array2)

array([[ 6,  7, 10],
       [ 8,  8, 12],
       [ 7,  6, 10]])

In [72]:
# broadcasting

array_0 = np.zeros((3, 4), dtype=int)
print(f"Array:\n{array_0}")

Array:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [73]:
array_0 + 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [77]:
# behind the scene
# [0, 0, 0, 0]     [5, 5, 5, 5]     [0, 0, 0, 0]     [0, 0, 0, 0]     [5, 5, 5, 5]
# [0, 0, 0, 0]  +  [0, 0, 0, 0]  +  [5, 5, 5, 5]  +  [0, 0, 0, 0]  =  [5, 5, 5, 5]
# [0, 0, 0, 0]     [0, 0, 0, 0]     [0, 0 ,0, 0]     [5, 5, 5, 5]     [5, 5, 5, 5]

In [75]:
array_0 + [1, 2, 3, 4]

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [78]:
# brhind the scene
# [0, 0, 0, 0]     [1, 2, 3, 4]     [0, 0, 0, 0]     [0, 0, 0, 0]     [1, 2, 3, 4]
# [0, 0, 0, 0]  +  [0, 0, 0, 0]  +  [1, 2, 3, 4]  +  [0, 0, 0, 0]  =  [1, 2, 3, 4]
# [0, 0, 0, 0]     [0, 0, 0, 0]     [0, 0 ,0, 0]     [1, 2, 3, 4]     [1, 2, 3, 4]

In [88]:
# transpose >> convert rows to columns and columns to rows
original_array = np.array([[1, 2, 3, 4, 5]])
print(f"Original Array:\n{original_array}\n{"***"*12}")
print(f"Transposed Array:\n{original_array.T}")

Original Array:
[[1 2 3 4 5]]
************************************
Transposed Array:
[[1]
 [2]
 [3]
 [4]
 [5]]


In [91]:
a = np.zeros((3, 3), dtype=int) + [1, 2, 3]
print(f"Original Array:\n{a}\n{"***"*12}")
print(f"Transposed Array:\n{a.T}")

Original Array:
[[1 2 3]
 [1 2 3]
 [1 2 3]]
************************************
Transposed Array:
[[1 1 1]
 [2 2 2]
 [3 3 3]]
