In [1]:
import numpy as np

In [2]:
array_1 = np.random.randint(1, 3, (3, 3))
array_2 = np.random.randint(1, 3, (3, 3))

print(f"Array 1:\n{array_1}\n{"**"*12}")
print(f"Array 2:\n{array_2}")

Array 1:
[[2 1 2]
 [2 2 2]
 [1 2 1]]
************************
Array 2:
[[1 2 1]
 [2 1 2]
 [2 1 1]]


In [3]:
# flatten() >> return a 1D array from the original array of any dimention
array_1.flatten()

array([2, 1, 2, 2, 2, 2, 1, 2, 1])

In [5]:
# the size of both the array remains the same
print(f"Original array size: {array_1.size}")
print(f"Flatten array size: {array_1.flatten().size}")

Original array size: 9
Flatten array size: 9


In [6]:
# expand dimention
array_3 = np.array([1, 2, 3, 4])
print(f"Array:\n{array_3}\nDimention: {array_3.ndim}D")

Array:
[1 2 3 4]
Dimention: 1D


In [8]:
# increase the dimention by 1 in the provided axis
# 0 -> x axis
# 1 -> y axis
np.expand_dims(array_3, axis=0) # expanded on: x-axis

array([[1, 2, 3, 4]])

In [9]:
np.expand_dims(array_3, axis=1) # expanded on: y-axis

array([[1],
       [2],
       [3],
       [4]])

In [25]:
print(f"Array:\n{array_2}\n")
array_expand = np.expand_dims(array_2, axis=0)
print(f"Expended array:\n{array_expand}")

Array:
[[1 2 1]
 [2 1 2]
 [2 1 1]]

Expended array:
[[[1 2 1]
  [2 1 2]
  [2 1 1]]]


In [18]:
array_a = np.array([[1], [2], [3]])
print(f"Array:\n{array_a}\nDimention: {array_a.ndim}D")

Array:
[[1]
 [2]
 [3]]
Dimention: 2D


In [19]:
# sqweezing the dimention
np.squeeze(array_a) # remove/lower 1 dimention from the original array

array([1, 2, 3])

In [22]:
# repeating the elements of an array
np.repeat(array_a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [27]:
print(f"Original array:\n{array_1}")
array_a_repeated = np.repeat(array_1, 2)
print(f"Repeated array: {array_a_repeated}")

Original array:
[[2 1 2]
 [2 2 2]
 [1 2 1]]
Repeated array: [2 2 1 1 2 2 2 2 2 2 2 2 1 1 2 2 1 1]


In [28]:
# repeating elements in rows
np.repeat(array_1, 2, axis=0)

array([[2, 1, 2],
       [2, 1, 2],
       [2, 2, 2],
       [2, 2, 2],
       [1, 2, 1],
       [1, 2, 1]])

In [30]:
# repeating elements in columns
np.repeat(array_1, 3, axis=1)

array([[2, 2, 2, 1, 1, 1, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 2, 2, 2, 1, 1, 1]])

In [34]:
array_4 = np.array([[1], [2], [3]])
print("Array 4:\n", array_4)

Array 4:
 [[1]
 [2]
 [3]]


In [36]:
np.roll(array_4, -1) # shift places

array([[2],
       [3],
       [1]])

In [37]:
np.roll(array_4, -2)

array([[3],
       [1],
       [2]])

In [38]:
array_b = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(f"Original array:\n{array_b}\nDimention: {array_b.ndim}D")

Original array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Dimention: 2D


In [39]:
np.roll(array_b, -1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [42]:
np.roll(array_b, 2, axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [49]:
array_b > 5

array([[False, False],
       [False, False],
       [False,  True],
       [ True,  True]])

In [50]:
# operations on numpy array of string elements
array_c = np.array(["jkmjatin", "jkmloom", "jkmcode"])
print(f"Array: {array_c}")

Array: ['jkmjatin' 'jkmloom' 'jkmcode']


In [52]:
# make every letter upper-case
print(f"Upper case array: {np.char.upper(array_c)}")
# make 1st letter capital
print(f"Capitalized array: {np.char.capitalize(array_c)}")

Upper case array: ['JKMJATIN' 'JKMLOOM' 'JKMCODE']
Capitalized array: ['Jkmjatin' 'Jkmloom' 'Jkmcode']


In [56]:
# mathematical functions
print(f"Original array: {array_1}")
print("Sin value of the array:\n", np.sin(array_1))

Original array: [[2 1 2]
 [2 2 2]
 [1 2 1]]
Sin value of the array:
 [[0.90929743 0.84147098 0.90929743]
 [0.90929743 0.90929743 0.90929743]
 [0.84147098 0.90929743 0.84147098]]


In [55]:
np.cos(array_1)

array([[-0.41614684,  0.54030231, -0.41614684],
       [-0.41614684, -0.41614684, -0.41614684],
       [ 0.54030231, -0.41614684,  0.54030231]])

In [57]:
np.tan(array_1)

array([[-2.18503986,  1.55740772, -2.18503986],
       [-2.18503986, -2.18503986, -2.18503986],
       [ 1.55740772, -2.18503986,  1.55740772]])

In [59]:
np.log10(array_1)

array([[0.30103, 0.     , 0.30103],
       [0.30103, 0.30103, 0.30103],
       [0.     , 0.30103, 0.     ]])

In [60]:
np.exp(array_1)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183]])

In [61]:
np.power(array_1, 3)

array([[8, 1, 8],
       [8, 8, 8],
       [1, 8, 1]])

In [62]:
np.max(array_1)

np.int64(2)

In [63]:
np.mean(array_1)

np.float64(1.6666666666666667)

In [64]:
np.min(array_1)

np.int64(1)

In [65]:
np.std(array_1)

np.float64(0.4714045207910317)

In [66]:
np.var(array_1)

np.float64(0.2222222222222222)

In [67]:
np.subtract(array_1, array_2)

array([[ 1, -1,  1],
       [ 0,  1,  0],
       [-1,  1,  0]])

In [68]:
np.multiply(array_1, array_2)

array([[2, 2, 2],
       [4, 2, 4],
       [2, 2, 1]])

In [69]:
np.mod(array_1, array_2) # return remender element wise

array([[0, 1, 0],
       [0, 0, 0],
       [1, 0, 0]])

In [70]:
np.sqrt(array_1)

array([[1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.        ]])

In [73]:
# sorting and searching in numpy array
array_5 = np.array([5, 6, 1, 2])
print(f"Array: {array_5}")
print(f"Sorted array: {np.sort(array_5)}")

Array: [5 6 1 2]
Sorted array: [1 2 5 6]


In [72]:
np.sort(array_5)

array([1, 2, 5, 6])

In [74]:
array_6 = np.array([5, 199, 200, 6, 7, 8])
print(f"Array: {array_6}")

Array: [  5 199 200   6   7   8]


In [75]:
np.sort(array_6)

array([  5,   6,   7,   8, 199, 200])

In [80]:
# add an element such that the array is sorted
np.searchsorted(array_6, 170)

np.int64(6)

In [81]:
array_6 = np.array([5, 199, 2000, 0, 0, 0, 0, 0, 6, 7, 8])
print(f"Array: {array_6}")

Array: [   5  199 2000    0    0    0    0    0    6    7    8]


In [82]:
np.count_nonzero(array_6)

np.int64(6)

In [83]:
print(f"Array: {array_6}")
print(f"Count of non zero elements: {np.count_nonzero(array_6)}")

Array: [   5  199 2000    0    0    0    0    0    6    7    8]
Count of non zero elements: 6


In [85]:
# elements greater than 0
array_6 > 0

array([ True,  True,  True, False, False, False, False, False,  True,
        True,  True])

In [87]:
np.where(array_6 > 0)
# returns index values

(array([ 0,  1,  2,  8,  9, 10]),)

In [88]:
np.extract(array_6 > 0, array_6)

array([   5,  199, 2000,    6,    7,    8])

In [89]:
array_6.byteswap()
# swap the bytes of the array elements

array([  360287970189639680, -4107282860161892352, -3456794188983566336,
                          0,                    0,                    0,
                          0,                    0,   432345564227567616,
         504403158265495552,   576460752303423488])

In [90]:
import numpy.matlib as nm
# numpy has this special module for mtrix

In [91]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [92]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [93]:
# numpy linear algebra function
array_1, array_2

(array([[2, 1, 2],
        [2, 2, 2],
        [1, 2, 1]]),
 array([[1, 2, 1],
        [2, 1, 2],
        [2, 1, 1]]))

In [94]:
array_1 @ array_2

array([[ 8,  7,  6],
       [10,  8,  8],
       [ 7,  5,  6]])

In [96]:
# determinant of a matrix
np.linalg.det(array_1)

np.float64(0.0)

In [97]:
np.linalg.det(array_2)

np.float64(2.9999999999999996)

In [100]:
# in matrix we can't divide by another matrix
# instead we have inverse
np.linalg.inv(array_2)
# inverse can not be calculated if determinant = 0

array([[-0.33333333, -0.33333333,  1.        ],
       [ 0.66666667, -0.33333333,  0.        ],
       [-0.        ,  1.        , -1.        ]])

In [104]:
# solving the below equations using numpy.matlib
# 7x + 5.3y -3z = 16
# 3x - 5y + 2z = 8
# 5x + 3y - 7z = 0
a = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])
print(f"Array:\n{a}")

Array:
[[ 7.   5.3 -3. ]
 [ 3.  -5.   2. ]
 [ 5.   3.  -7. ]]


In [105]:
b = np.array([16, 8, 0])

In [106]:
np.linalg.solve(a, b)

array([2.59630607, 0.84432718, 2.21635884])