# Numpy Revision
June 1st, 2026

In [49]:
my_list = [1, 2, 3, 4, 5]

In [50]:
my_list

[1, 2, 3, 4, 5]

In [51]:
import numpy as np

In [52]:
arr = np.array(my_list)

In [53]:
arr

array([1, 2, 3, 4, 5])

In [54]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [55]:
np_my_mat = np.array(my_mat)
np_my_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
print(type(my_list))
print(type(np_my_mat))

<class 'list'>
<class 'numpy.ndarray'>


In [57]:
np.arange(0, 10) # default step size of 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.arange(0, 10, 2) # step size of 2

array([0, 2, 4, 6, 8])

In [59]:
np.zeros(5) # array of zeros with length 5

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros(5, dtype=int) # array of zeros with length 5 and integer data type

array([0, 0, 0, 0, 0])

In [61]:
np.zeros((5, 5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [62]:
np.linspace(0, 10, 3) # 3 evenly spaced numbers between 0 and 10

array([ 0.,  5., 10.])

In [63]:
# identity matrix
np.eye(5) # default data type is float

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
np.eye(5, dtype=int) # identity matrix with integer data type

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [65]:
# array of random numbers between 0 and 1 with length 5
np.random.rand(5)

array([0.72632199, 0.01098621, 0.0542765 , 0.30002488, 0.40906507])

In [66]:
np.random.rand(5, 5)

array([[0.07292263, 0.99435268, 0.94774609, 0.5741718 , 0.40128656],
       [0.21613033, 0.13007861, 0.90193507, 0.43796736, 0.63265339],
       [0.29105426, 0.15224901, 0.78271067, 0.78320558, 0.85113023],
       [0.10676132, 0.08069709, 0.63543499, 0.37112502, 0.7291816 ],
       [0.93022844, 0.8158874 , 0.87575819, 0.03983899, 0.31661743]])

In [67]:
np.random.randn(2)

array([-1.15522555,  0.89319347])

In [68]:
# get a random integer for a defined range
np.random.randint(1, 100)

41

In [69]:
np.random.randint(1, 100, 5)

array([58, 69, 39,  4, 66])

In [70]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([10,  3,  2, 18, 27, 13, 11, 23, 39, 29])

In [ ]:
# reshaping an array
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
print(ranarr)
ranarr.max()

[10  3  2 18 27 13 11 23 39 29]


np.int64(39)

In [74]:
ranarr.min()

np.int64(2)

In [78]:
ranarr.argmax() # o/p: index value of the max value

np.int64(8)

In [79]:
ranarr.argmin()

np.int64(2)

In [81]:
ranarr.shape

(10,)

In [82]:
ranarr.dtype

dtype('int64')

In [83]:
type(ranarr)

numpy.ndarray