# 01: numpy revision
numpy is a library for the python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [14]:
import numpy as np
import time

In [9]:
# creating array from list
array_1d = [1, 2, 3, 4, 5]
print(f"array 1d: {np.array(array_1d)}\n{'***'*7}") # 1d array

array_2d = np.array([[1, 2, 3], [4, 5, 6]]) # 2d array
print(f"array 2d:\n{array_2d}")

array 1d: [1 2 3 4 5]
*********************
array 2d:
[[1 2 3]
 [4 5 6]]


### **list vs numpy.array()**

In [13]:
py_list = [1, 2, 3] # creating python_list
print(f"python_list multiplication: {py_list*2}") # list multiplication

np_array = np.array([1, 2, 3]) # creating numpy.array
print(f"numpy.array multiplication: {np_array*2}") # np.array() multiplication

python_list multiplication: [1, 2, 3, 1, 2, 3]
numpy.array multiplication: [2 4 6]


In [21]:
# execution time for python_list
start = time.time()
py_list = [i*2 for i in range(1000000)]
print(f"\n(python_list) list operaiton time {time.time() - start} seconds.")

# execution time for numpy.array()
start = time.time()
np_array = np.arange(1000000) * 2
print(f"\n(numpy.array()) np.array operaiton time {time.time() - start} seconds.")


(python_list) list operaiton time 0.06010699272155762 seconds.

(numpy.array()) np.array operaiton time 0.009226560592651367 seconds.


**result:** numpy.array() generally executes faster for larger numbers than python_list

### **array creation from scratch**

In [26]:
zeros = np.zeros((5, 5), dtype=int) # creating 5,5 zero array
print(f"zero array [2d] (5, 5)\n{zeros}")

zero array [2d] (5, 5)
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [29]:
ones = np.ones((5, 5), dtype=int) # creating 5,5 ones array
print(f"ones array [2d] (5, 5)\n{ones}")

ones array [2d] (5, 5)
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [31]:
# creating an array of constant (7) for a 5,5 matrix (or 2d np.array())
full = np.full((5, 5), 7)
print(f"constant array of (5, 5) where condtant=7\n{full}")

constant array of (5, 5) where condtant=7
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [36]:
# np.random >> is not a method but a class with many methods
# so we use np.random.random()
random = np.random.random((5, 5)) # creating an array of random values (5, 5)
print(f"(5, 5) array of random values\n{random}")
# these random values ranges from 0 to 1

(5, 5) array of random values
[[0.15486377 0.03861037 0.92730066 0.5533578  0.11636262]
 [0.76268797 0.22186159 0.87629076 0.04674577 0.82171869]
 [0.66559222 0.56280709 0.53877611 0.823858   0.29039007]
 [0.93272751 0.00714862 0.55264737 0.58244061 0.70531741]
 [0.55281214 0.85250621 0.48484903 0.58110284 0.08525202]]


In [40]:
# creating sequential array
sequence = np.arange(0, 11, 2) # range in python is always a non-inclusive ouoter boundry
print(f"sequential array 1d: {sequence}")

sequential array 1d: [ 0  2  4  6  8 10]


### **vector, matrix & tensor**

In [42]:
# creating a vector
vector = np.array([1, 2, 3, 4, 5])
print(f"vector: {vector}")

vector: [1 2 3 4 5]


In [43]:
# creating a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# matrix refers to 2d array
print(f"matrix:\n{matrix}")

matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
# creating tensor
tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
# tensor >> multi-dimentional arrays
print(f"tensor:\n{tensor}")

tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### **array properties**

In [64]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(f"array:\n{arr}\n{'-----'*5}")
print(f"shape: {arr.shape}")
print(f"dimantion: {arr.ndim}D")
print(f"size: {arr.size}") # no. of elements
print(f"dtype (data-type): {arr.dtype}")
# there are more properties but we're looking at the most common ones

array:
[[1 2 3]
 [4 5 6]]
-------------------------
shape: (2, 3)
dimantion: 2D
size: 6
dtype (data-type): int64


### **array reshaping**

In [68]:
# creating an 1d array to be reshaped
arr = np.arange(12)
print(f"original array: {arr}")

original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [80]:
print(f"original array (1d): {arr}\n{'-----'*11}")
# reshaping the array
reshaped = arr.reshape((3, 4))
print(f"reshaped array 2d:(3, 4):\n{reshaped}")

original array (1d): [ 0  1  2  3  4  5  6  7  8  9 10 11]
-------------------------------------------------------
reshaped array 2d:(3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [84]:
print(f"source array:\n{reshaped}\n{'-----'*11}")
# flatting an array: making an array 1d
flattened = reshaped.flatten()
print(f"flattened array: {flattened}")

source array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------------------------
flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [87]:
# .ravel() >> returns view intead of copy
raveled = reshaped.ravel()
print(f"raveled array: {raveled}")

raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [93]:
print(f"source array:\n{reshaped}")
print(f"{'-----'*4}")
# tanspose of a matrix (2d array)
transpose = reshaped.T
print(f"transposed array:\n{transpose}")

source array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
transposed array:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
