# 02: numpy revision

In [1]:
import numpy as np

### **indexing & slicing**

In [4]:
# creatnig an array to work with
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
# slicing an 1d array
print(f"basic slicing >> arr[2:7] -> {arr[2:7]}")
print(f"with step >> arr[1:8:2] -> {arr[1:8:2]}")
print(f"negative indexing >> arr[-3] -> {arr[-3]}")

basic slicing >> arr[2:7] -> [3 4 5 6 7]
with step >> arr[1:8:2] -> [2 4 6 8]
negative indexing >> arr[-3] -> 8


In [10]:
# creating an 2d array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(f"2d array:\n{arr_2d}")

2d array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# slicing an 2d array
print(f"speicfic element >> arr_2d[1, 2] -> {arr_2d[1, 2]}")
# syntax: array_var_name[row, column]

speicfic element >> arr_2d[1, 2] -> 6


In [19]:
print(f"entire row arr_2d[1] -> {arr_2d[1]}") # syntax: array_var_name[row]
print(f"entire column arr_2d[:, 1] -> {arr_2d[:, 1]}") # syntax: array_var_name[:, column]

entire row arr_2d[1] -> [4 5 6]
entire column arr_2d[:, 1] -> [2 5 8]


### **sorting**

In [18]:
# basic sorting (1d array)
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print(f"unsorted array: {unsorted}")
print(f"sorted array: {np.sort(unsorted)}")

unsorted array: [3 1 4 1 5 9 2 6]
sorted array: [1 1 2 3 4 5 6 9]


In [26]:
# creating 2d array
arr_2d_unsorted = np.array([[3, 1],
                            [1, 2],
                            [2, 3]])
print(f"unsorted 2d array:\n{arr_2d_unsorted}\n{'-----'*7}")

# sorting 2d array: column
print(f"sorted 2d array by column:\n{np.sort(arr_2d_unsorted, axis=0)}")
# syntax: np.sort(arr_2d_unsorted, axis=0) >> axis=0=column

print(f"{'-----'*7}")

# sorting 2d array: row
print(f"sorted 2d array by row:\n{np.sort(arr_2d_unsorted, axis=1)}")
# syntax: np.sort(arr_2d_unsorted, axis=1) >> axis=1=row

unsorted 2d array:
[[3 1]
 [1 2]
 [2 3]]
-----------------------------------
sorted 2d array by column:
[[1 1]
 [2 2]
 [3 3]]
-----------------------------------
sorted 2d array by row:
[[1 3]
 [1 2]
 [2 3]]


### **filter**

In [3]:
numbers = np.arange(1, 11)
print(f"array (var_name: numbers) -> {numbers}")

array (var_name: numbers) -> [ 1  2  3  4  5  6  7  8  9 10]


In [31]:
# filtering even numbers
even_numbers = numbers[numbers % 2 == 0]
print(f"even numbers from numbers_array: {even_numbers}")

even numbers from numbers_array: [ 2  4  6  8 10]


### **filter with mask**

In [6]:
# mask filtering
mask = numbers > 5
print(f"numbers greater than 5 -> {numbers[mask]}")

numbers greater than 5 -> [ 6  7  8  9 10]


### **fancy indexing vs np.where()**

In [8]:
# simple fancy indices approch
indices = [0, 2, 4]
print(f"{numbers[indices]}")

[1 3 5]


In [14]:
# numpy.where() approch
where_result = np.where(numbers > 5)
print(f"where_result -> {where_result}")
print(f"np.where(numbers>5) -> {numbers[where_result]}")

where_result -> (array([5, 6, 7, 8, 9]),)
np.where(numbers>5) -> [ 6  7  8  9 10]


In [12]:
# np.where() >> creates array
condition_array = np.where(numbers > 5)
print(condition_array)

(array([5, 6, 7, 8, 9]),)


In [27]:
condition_array = np.where(numbers>5, numbers*4, numbers)
# syntax >> np.where(condition, x, y) >> x=True for condition, y=Flase for condition
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


In [32]:
# undertanding of np.where()
print(np.where(numbers>5, 'T', 'F'))

['F' 'F' 'F' 'F' 'F' 'T' 'T' 'T' 'T' 'T']


### **combining/concatenate and adding arrays**

In [33]:
# creating arrays to work on
arr_1 = np.array([1, 2 ,3])
arr_2 = np.array([4, 5, 6])

In [36]:
# combining/concatenating arrays
combined = np.concatenate((arr_1, arr_2))
print(combined)

[1 2 3 4 5 6]


In [37]:
# adding arrays
added = arr_1 + arr_2
print(added)

[5 7 9]


### **array compatibility**

In [41]:
# creating arrays to work on
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

In [42]:
print(f"compatibility shapes (a & b) -> {a.shape == b.shape}")

compatibility shapes (a & b) -> False


### **adding new rows and new columns to an array**

In [56]:
# adding a row to the original array
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
# syntax >> np.vstack((tup)) >> used for adding row

print(f"original ->\n{original}\n{'---'*5}")
print(f"new row -> {new_row}\n{'---'*5}")
print(f"resultant array with new row ->\n{with_new_row}")

original ->
[[1 2]
 [3 4]]
---------------
new row -> [[5 6]]
---------------
resultant array with new row ->
[[1 2]
 [3 4]
 [5 6]]


In [57]:
# adding a column in the original array
new_col = np.array([[1], [8]])

with_new_col = np.hstack((original, new_col))
# syntax >> np.hstack((tup)) >> used for adding column

print(f"original ->\n{original}\n{'---'*5}")
print(f"new column ->\n{new_col}\n{'---'*5}")
print(f"resultant array with column ->\n{with_new_col}")

original ->
[[1 2]
 [3 4]]
---------------
new column ->
[[1]
 [8]]
---------------
resultant array with column ->
[[1 2 1]
 [3 4 8]]


### **remove/delete operations in array**

In [61]:
# creating array to work on
arr = np.array([0, 1, 2, 3, 4, 5])

# deleting index value from the array
deleted = np.delete(arr, 2)
# syntax >> np.delete(array_variable, index_value)

print(f"original array -> {arr}")
print(f"array after deletion -> {deleted}")

original array -> [0 1 2 3 4 5]
array after deletion -> [0 1 3 4 5]
